// 音源・エフェクトのつまみの名前と説明の英語(つまみの定義〈glaux-dsp の ParamSpec〉は日本語の表示名と AI 向けの説明を持つ)。
// 英語のときだけ、ここの対訳を出す。kind は音源・エフェクトの種類(subtractive / reverb など。分からなければ null)、
// name はつまみの名前(cutoff など。定義の name)。表に無ければ、名前を読みやすくしたもの(filter_env → Filter env)
import { isEn } from "./i18n.svelte";

/** つまみの表示名の英語(`kind:name` か `name` で引く) */
const LABEL_EN: Record<string, string> = {
  // 種類をまたいで共通
  "algorithm": "Algorithm",
  "amount": "Amount",
  "analog": "Analog",
  "attack": "Attack",
  "attack_db": "Attack",
  "attack_ms": "Attack",
  "bits": "Bit depth",
  "brightness": "Brightness",
  "cab": "Cabinet",
  "ceiling_db": "Ceiling",
  "center_hz": "Center",
  "cents": "Cents",
  "character": "Character",
  "crackle": "Crackle",
  "curve": "Curve",
  "cutoff": "Cutoff",
  "decay": "Decay",
  "decay_ms": "Decay",
  "decorrelate": "Decorrelate",
  "delay_ms": "Delay",
  "density": "Density",
  "depth": "Depth",
  "depth_db": "Depth",
  "depth_ms": "Depth",
  "detector": "Detector",
  "detune": "Detune",
  "downsample": "Downsample",
  "drive": "Drive",
  "drive_db": "Drive",
  "dyn_attack_ms": "Dynamic attack",
  "dyn_release_ms": "Dynamic release",
  "early": "Early reflections",
  "env_amount": "Envelope amount",
  "feedback": "Feedback",
  "filter_attack": "Filter attack",
  "filter_decay": "Filter decay",
  "filter_env": "Filter env",
  "filter_sustain": "Filter sustain",
  "filter_type": "Filter type",
  "flutter": "Flutter",
  "formant_db": "Formant gain",
  "formant_hz": "Formant freq",
  "formant_width": "Formant width",
  "freq": "Frequency",
  "gain_db": "Gain",
  "gate_ms": "Gate",
  "grain_ms": "Grain size",
  "hat_decay": "Hi-hat decay",
  "high_gain_db": "High gain",
  "high_hz": "High limit",
  "high_mult": "High decay ×",
  "high_ratio": "High ratio",
  "high_threshold_db": "High threshold",
  "hiss": "Hiss",
  "hold_ms": "Hold",
  "hp_freq": "High-pass",
  "hysteresis_db": "Hysteresis",
  "index": "Mod index",
  "index_decay": "Index decay",
  "index_sustain": "Index sustain",
  "inharmonic": "Inharmonicity",
  "input_db": "Input",
  "interval1": "Voice 1 interval",
  "interval2": "Voice 2 interval",
  "ir": "Impulse response",
  "key": "Key",
  "key_track": "Key tracking",
  "kick_decay": "Kick decay",
  "kick_punch": "Kick punch",
  "kick_tune": "Kick tune",
  "kit": "Kit",
  "knee_db": "Knee",
  "length": "Length",
  "level_db": "Level",
  "lfo1_depth": "LFO1 depth",
  "lfo1_rate": "LFO1 rate",
  "lfo1_shape": "LFO1 shape",
  "lfo1_target": "LFO1 target",
  "lfo2_depth": "LFO2 depth",
  "lfo2_rate": "LFO2 rate",
  "lfo2_shape": "LFO2 shape",
  "lfo2_target": "LFO2 target",
  "lfo_depth": "LFO depth",
  "lfo_rate": "LFO rate",
  "lookahead_ms": "Lookahead",
  "loop": "Loop",
  "loop_end": "Loop end",
  "loop_start": "Loop start",
  "loop_xfade_ms": "Loop crossfade",
  "low_gain_db": "Low gain",
  "low_hz": "Low limit",
  "low_mult": "Low decay ×",
  "low_ratio": "Low ratio",
  "low_threshold_db": "Low threshold",
  "lp_freq": "Low-pass",
  "makeup_db": "Makeup",
  "mid_freq": "Mid freq",
  "mid_gain_db": "Mid gain",
  "mid_q": "Mid Q",
  "mid_ratio": "Mid ratio",
  "mid_threshold_db": "Mid threshold",
  "mix": "Mix",
  "mod1_amp": "MOD1 → amp",
  "mod1_cutoff": "MOD1 → cutoff",
  "mod1_drive": "MOD1 → drive",
  "mod1_hz": "MOD1 rate (Hz)",
  "mod1_pan": "MOD1 → pan",
  "mod1_phase": "MOD1 phase",
  "mod1_pitch": "MOD1 → pitch",
  "mod1_points": "MOD1 curve",
  "mod1_position": "MOD1 → position",
  "mod1_rate": "MOD1 rate",
  "mod1_res": "MOD1 → res",
  "mod1_retrig": "MOD1 retrigger",
  "mod1_shape": "MOD1 shape",
  "mod1_warp": "MOD1 → warp",
  "mod2_amp": "MOD2 → amp",
  "mod2_cutoff": "MOD2 → cutoff",
  "mod2_drive": "MOD2 → drive",
  "mod2_hz": "MOD2 rate (Hz)",
  "mod2_pan": "MOD2 → pan",
  "mod2_phase": "MOD2 phase",
  "mod2_pitch": "MOD2 → pitch",
  "mod2_points": "MOD2 curve",
  "mod2_position": "MOD2 → position",
  "mod2_rate": "MOD2 rate",
  "mod2_res": "MOD2 → res",
  "mod2_retrig": "MOD2 retrigger",
  "mod2_shape": "MOD2 shape",
  "mod2_warp": "MOD2 → warp",
  "mode": "Mode",
  "modulation": "Modulation",
  "mono_below_hz": "Mono below",
  "noise": "Noise",
  "noise_color": "Noise color",
  "odd_even": "Odd/even",
  "op1_attack": "OP1 attack",
  "op1_decay": "OP1 decay",
  "op1_level": "OP1 level",
  "op1_ratio": "OP1 ratio",
  "op1_sustain": "OP1 sustain",
  "op2_attack": "OP2 attack",
  "op2_decay": "OP2 decay",
  "op2_level": "OP2 level",
  "op2_ratio": "OP2 ratio",
  "op2_sustain": "OP2 sustain",
  "op3_attack": "OP3 attack",
  "op3_decay": "OP3 decay",
  "op3_level": "OP3 level",
  "op3_ratio": "OP3 ratio",
  "op3_sustain": "OP3 sustain",
  "op4_attack": "OP4 attack",
  "op4_decay": "OP4 decay",
  "op4_level": "OP4 level",
  "op4_ratio": "OP4 ratio",
  "op4_sustain": "OP4 sustain",
  "orig_bpm": "Original tempo",
  "osc_level": "Osc level",
  "output_db": "Output",
  "partials": "Partials",
  "pattern": "Pattern",
  "pick": "Pick",
  "ping_pong": "Ping-pong",
  "pitch_rand": "Pitch random",
  "pos_decay": "Position env decay",
  "pos_env": "Position env",
  "position": "Position",
  "predelay_ms": "Pre-delay",
  "presence": "Presence",
  "q": "Q",
  "range_db": "Range",
  "rate_hz": "Rate",
  "ratio": "Ratio",
  "release": "Release",
  "release_ms": "Release",
  "remove_lows": "Remove lows",
  "resonance": "Resonance",
  "root": "Root note",
  "sample": "Sample",
  "saturation": "Saturation",
  "sc_hpf_hz": "Sidechain HPF",
  "scale": "Scale",
  "scan": "Scan",
  "semitones": "Semitones",
  "shape": "Shape",
  "shimmer": "Shimmer",
  "size": "Size",
  "slices": "Slices",
  "smooth_ms": "Smoothing",
  "snare_snappy": "Snare snappy",
  "snare_tune": "Snare tune",
  "source": "Sidechain track",
  "speed_ms": "Speed",
  "spray_ms": "Spray",
  "spread": "Spread",
  "stages": "Stages",
  "stereo": "Stereo",
  "sub": "Sub osc",
  "sustain": "Sustain",
  "sustain_db": "Sustain",
  "sync": "Sync",
  "table": "Table",
  "taps": "Taps",
  "threshold_db": "Threshold",
  "tilt": "Tilt",
  "time_ms": "Time",
  "tone": "Tone",
  "tune": "Tune",
  "type": "Type",
  "unison": "Unison",
  "vel_bright": "Velocity → brightness",
  "vel_cutoff": "Velocity → cutoff",
  "voices": "Voices",
  "warp": "Warp",
  "warp_amount": "Warp amount",
  "waveform": "Waveform",
  "wet_db": "Wet level",
  "width": "Width",
  "window": "Grain shape",
  "wobble": "Wobble",
  "wow": "Wow",
  // additive
  "additive:damping": "High damping",
  // eq
  "eq:low_freq": "Low freq",
  "eq:high_freq": "High freq",
  // reverb
  "reverb:damping": "Damping",
  // sidechain
  "sidechain:source": "Source track",
  "sidechain:duck_db": "Duck depth",
  // delay
  "delay:duck_db": "Ducking",
  // multiband
  "multiband:low_freq": "Low crossover",
  "multiband:high_freq": "High crossover",
  // dynamic_eq
  "dynamic_eq:range_db": "Max cut",
  // virtual_bass
  "virtual_bass:freq": "Bass limit",
  // volume_shaper
  "volume_shaper:sync": "Period",
};

/** つまみの説明の英語(`kind:name` か `name` で引く) */
const DESC_EN: Record<string, string> = {
  // 種類をまたいで共通
  "analog": "Analog-style drift: small per-voice pitch offsets, slowly wandering pitch and brightness, and per-note level variation, so repeated notes sound slightly different each time (a 'living' sound). 0.2-0.4 is natural; 0.7+ sounds like unstable vintage gear.",
  "decay": "Time to fall to the sustain level after the attack.",
  "drive": "Gentle distortion before the filter. Adds harmonics for a thicker, more forward sound (analog bass and leads). 0.2-0.4 for weight, 0.7+ for a gritty, aggressive tone.",
  "filter_attack": "Time for the filter envelope to fully open (only when filter_decay is above 0). Longer values make the sound brighten slowly after the note starts (a swelling, wah-like pad).",
  "filter_decay": "Separates the filter envelope from the amp envelope. 0 follows the amp ADSR (original behavior). 0.1-0.4 gives a bright 'pluck' or bass attack while the volume sustains; 1+ for pads that slowly darken. The opening amount is filter_env.",
  "filter_sustain": "How open the filter stays after the filter envelope decays (only when filter_decay is above 0). At 0 it closes back down to the cutoff value.",
  "filter_type": "lp12 is a 12 dB lowpass (the original sound); lp24 is a steeper, fatter lowpass (analog bass and pads); hp cuts the lows for a thin, light sound; bp keeps only the mids (telephone, radio, nasal); notch removes only the area around the cutoff (phaser-like hollowness).",
  "gain_db": "Level of the instrument itself, separate from the track volume.",
  "key_track": "How much the cutoff rises for higher notes. At 0 high notes tend to sound muffled and low notes loud; at 1 the cutoff follows pitch (same brightness in every register). Around 0.5 sounds natural.",
  "lfo1_depth": "Depth of LFO1; 0 = off. Typical values depend on the target: pitch 0.05-0.1 (vibrato), cutoff 0.2-0.6 (wah, wobble), amp 0.3-0.7 (tremolo), pan 0.3-0.8.",
  "lfo1_rate": "Speed of LFO1. Vibrato 4-6 Hz, wah or wobble 1-8 Hz, slowly moving pads 0.1-0.5 Hz.",
  "lfo1_shape": "Shape of LFO1. sine and triangle are smooth; square switches between two values (trills, chops); saw is a repeating ramp; random jumps to a new value each cycle (sample & hold, for irregular electronic motion).",
  "lfo1_target": "What LFO1 moves: pitch (vibrato), cutoff (wah, wobble), amp (tremolo), pan (auto-pan), position (wavetable position; wavetable only), warp (wavetable warp amount; wavetable only).",
  "lfo2_depth": "Depth of LFO2 (0 = off).",
  "lfo2_rate": "Speed of LFO2 (works like LFO1; use it to add a second target at a different speed).",
  "lfo2_shape": "Shape of LFO2 (same as LFO1).",
  "lfo2_target": "What LFO2 moves (same as LFO1).",
  "mix": "Blend with the dry sound.",
  "mod1_amp": "Amount sent to the volume (1 = the troughs are silent; negative inverts it). For chopped, gate-like motion. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod1_cutoff": "Amount sent to the cutoff (±1 = ±4 octaves). The main 'wah' of a wobble: set the cutoff fairly low and use 0.4-0.8. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod1_drive": "Amount sent to the drive before the filter (±1). Gets grittier as it opens. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod1_hz": "Above 0, the modulator runs freely at this rate in Hz instead of following the tempo (overrides mod1_rate). 0 = tempo-synced.",
  "mod1_pan": "Amount sent to the pan (±1 = all the way left/right). 0 = off. One modulator can feed several targets (mod matrix).",
  "mod1_phase": "Where the cycle starts (0-1; 0.5 shifts it by half a cycle).",
  "mod1_pitch": "Amount sent to pitch (±1 = ±12 semitones). Small amounts (0.02-0.05) add a slight beating; large amounts give wobbles where the pitch drops or jumps. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod1_points": "One cycle's shape when mod1_shape is custom: \"x,y[,curve]; x,y; ...\" (x ascending from 0 to 1, y from -1 to 1, curve from -1 to 1 where positive starts slowly). Repeating the same x makes a step. Up to 16 points. Example: \"0,-1; 0.1,1,-0.5; 1,-1,0.6\" (opens fast, closes slowly).",
  "mod1_position": "Amount sent to the wavetable position (±1 = one end of the table to the other; wavetable only). The heart of talking wobbles and growls. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod1_rate": "Rate of per-voice modulator 1, in cycles per beat (quarter note), so it follows the tempo: 1/1 = 0.25, 1/2 = 0.5, 1/4 = 1, 1/4d = 0.667, 1/8 = 2, 1/8d = 1.333, 1/8t = 3, 1/16 = 4, 1/16t = 6, 1/32 = 8. Switching it every beat with automation (write_wobble) makes the wobble 'talk' by changing speed. When mod1_hz is above 0, that is used instead.",
  "mod1_res": "Amount sent to the resonance (±1 = ±0.9). The filter rings harder as it opens. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod1_retrig": "note = restarts at each note (the same motion on every note; the basis of short chopped wobbles). song = locked to the song's beat (all notes stay aligned, and long notes re-align on the beat; best when changing the rate every beat).",
  "mod1_shape": "Shape of the modulation. sine and triangle are smooth, square switches between two values, saw_up / saw_down are ramps, random jumps each cycle. wub opens fast and closes slowly (the classic wobble), saw_down_curve opens then closes exponentially ('bwow'), yoi has two peaks per cycle ('yoi-yoi'), stairs is a 4-step staircase. custom uses your own curve from mod1_points.",
  "mod1_warp": "Amount sent to the wavetable warp amount (±1; wavetable only; set warp to something other than none). 0 = off. One modulator can feed several targets (mod matrix).",
  "mod2_amp": "Amount sent to the volume (1 = the troughs are silent; negative inverts it). For chopped, gate-like motion. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod2_cutoff": "Amount sent to the cutoff (±1 = ±4 octaves). The main 'wah' of a wobble: set the cutoff fairly low and use 0.4-0.8. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod2_drive": "Amount sent to the drive before the filter (±1). Gets grittier as it opens. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod2_hz": "Above 0, the modulator runs freely at this rate in Hz instead of following the tempo (overrides mod2_rate). 0 = tempo-synced.",
  "mod2_pan": "Amount sent to the pan (±1 = all the way left/right). 0 = off. One modulator can feed several targets (mod matrix).",
  "mod2_phase": "Where the cycle starts (0-1; 0.5 shifts it by half a cycle).",
  "mod2_pitch": "Amount sent to pitch (±1 = ±12 semitones). Small amounts (0.02-0.05) add a slight beating; large amounts give wobbles where the pitch drops or jumps. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod2_points": "One cycle's shape when mod2_shape is custom: \"x,y[,curve]; x,y; ...\" (x ascending from 0 to 1, y from -1 to 1, curve from -1 to 1 where positive starts slowly). Repeating the same x makes a step. Up to 16 points. Example: \"0,-1; 0.1,1,-0.5; 1,-1,0.6\" (opens fast, closes slowly).",
  "mod2_position": "Amount sent to the wavetable position (±1 = one end of the table to the other; wavetable only). The heart of talking wobbles and growls. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod2_rate": "Rate of per-voice modulator 2, in cycles per beat (quarter note), so it follows the tempo: 1/1 = 0.25, 1/2 = 0.5, 1/4 = 1, 1/4d = 0.667, 1/8 = 2, 1/8d = 1.333, 1/8t = 3, 1/16 = 4, 1/16t = 6, 1/32 = 8. Switching it every beat with automation (write_wobble) makes the wobble 'talk' by changing speed. When mod2_hz is above 0, that is used instead.",
  "mod2_res": "Amount sent to the resonance (±1 = ±0.9). The filter rings harder as it opens. 0 = off. One modulator can feed several targets (mod matrix).",
  "mod2_retrig": "note = restarts at each note (the same motion on every note; the basis of short chopped wobbles). song = locked to the song's beat (all notes stay aligned, and long notes re-align on the beat; best when changing the rate every beat).",
  "mod2_shape": "Shape of the modulation. sine and triangle are smooth, square switches between two values, saw_up / saw_down are ramps, random jumps each cycle. wub opens fast and closes slowly (the classic wobble), saw_down_curve opens then closes exponentially ('bwow'), yoi has two peaks per cycle ('yoi-yoi'), stairs is a 4-step staircase. custom uses your own curve from mod2_points.",
  "mod2_warp": "Amount sent to the wavetable warp amount (±1; wavetable only; set warp to something other than none). 0 = off. One modulator can feed several targets (mod matrix).",
  "spread": "How far the unison voices are spread left and right. 0 = center, 0.5-0.8 = wide supersaws and pads. The center content is unchanged, so it doesn't thin out in mono. No effect with a single unison voice. Keep it at 0 for bass (keep the lows centered).",
  "sync": "Tempo-synced period (1/4 = quarter note, 1/8d = dotted 8th, 1/8t = 8th-note triplet, 1/1 = one bar). off uses rate_hz.",
  "vel_cutoff": "How much harder playing brightens and softer playing darkens the tone, for an acoustic-instrument feel. 0.3-0.6 is a good range (at 1 the softest notes are 3 octaves darker).",
  // subtractive
  "subtractive:waveform": "The basic character of the sound. saw is bright and thick, square is hollow and woodwind-like, triangle is round and soft, sine is the purest tone.",
  "subtractive:cutoff": "Lower it for a darker, muffled sound; raise it to open up and brighten. Rough guide: bass 200-800, pads 1000-3000, leads 3000 and up.",
  "subtractive:resonance": "Emphasis around the cutoff. Raising it gives the classic squelchy synth sound; too much becomes peaky and piercing.",
  "subtractive:attack": "How fast the sound rises. Short is percussive; long swells in softly, suited to pads.",
  "subtractive:decay": "How fast the level falls toward the sustain level after the attack (a time constant: with sustain at 0, the sound is nearly gone after about 7x this value). Short values give a plucked feel.",
  "subtractive:sustain": "Level while the key is held. Near 0 is plucky or staccato; near 1 holds like an organ.",
  "subtractive:release": "How long the sound takes to die away after the note ends (time to -60 dB). Long values add a reverberant tail but can muddy fast phrases.",
  "subtractive:filter_env": "How far the cutoff opens briefly at the start of each note. Raise it for the classic snappy synth attack.",
  "subtractive:unison": "Number of slightly detuned copies stacked on each note. 3-7 with detune gives the thick EDM supersaw. 1 = off (original behavior).",
  "subtractive:detune": "Spread of the unison voices (100 = one semitone). More is thicker and more swirling, but too much blurs the pitch. 15-30 for a supersaw.",
  "subtractive:sub": "Amount of sine wave one octave below. The foundation of a bass, the low end you feel in your chest. 0.5-1.0 is typical for EDM bass.",
  "subtractive:noise": "Amount of noise mixed in: breathiness, grit, a fizzy texture. With osc_level 0 it becomes a noise-only source (vinyl noise, wind, waves, noise risers).",
  "subtractive:noise_color": "white has equal energy across the spectrum (hiss; risers, hi-hat-like). pink gets weaker toward the top (rain, tape hiss, the bed of a vinyl record). brown leans even lower (wind, waves, rumble).",
  "subtractive:osc_level": "Level of the main waveform (saw etc.). At 0 only the noise and sub sound (unpitched effects, ambiences).",
  "subtractive:crackle": "How dense the vinyl crackle (sparse short clicks) is. 0.2-0.4 sounds like an old record, 0.7+ like a campfire. For lo-fi vinyl noise try osc_level 0, noise 0.1, noise_color pink, crackle 0.3.",
  "subtractive:gain_db": "Level of the instrument itself, separate from the track volume. Chords stack up, so lower it if they clip.",
  // drum
  "drum:decay": "Multiplier for the decay of every piece. Lower is tight and punchy; higher is loose and roomy.",
  "drum:gain_db": "Volume of the whole drum kit.",
  "drum:tone": "Brightness. Raise it for more kick click and more snare and hat highs that cut through; lower it for a rounder, lo-fi sound.",
  "drum:tune": "Shifts the pitch of the whole kit (kick, snare, toms, percussion) in semitones.",
  "drum:kit": "Kit type. modern is contemporary programmed drums (fat, driven kick, tight snare, bright hats; pop, EDM, programmed rock). 808 is TR-808 style (long, low booming kick as in trap and hip-hop 808s, thin snare, metallic hats and cowbell). 909 is TR-909 style (punchy kick, noisy snare, bright hats; house, techno).",
  "drum:kick_tune": "Kick pitch in semitones. Higher is tighter and lighter, lower is heavier and deeper. Tuning it to the song's root avoids clashing with the bass (modern at 0 is about 52 Hz ≈ G#1, 808 about 48 Hz).",
  "drum:kick_decay": "Length multiplier for the kick body. Short for tight, fast songs; long for an 808-style boom that also plays the bass role.",
  "drum:kick_punch": "Amount of attack click and drive. Higher gives a hard transient that's audible even on small speakers; lower is round and soft.",
  "drum:snare_tune": "Snare shell pitch in semitones. Higher gives a tight, cranked head (funk, pop); lower a fat, loose sound (rock ballads, lo-fi).",
  "drum:snare_snappy": "Amount of snare wires (the rattle). Higher is bright and splashy; lower brings the shell forward, closer to a tom.",
  "drum:hat_decay": "Hi-hat decay multiplier. Short for tight 'tick' patterns; long for an open, washy sound.",
  // sampler
  "sampler:cutoff": "Filter frequency (when filter_type is not off). For a lowpass, lower is darker and further away; for a highpass, higher is thinner and lighter.",
  "sampler:resonance": "Emphasis around the cutoff. Higher gives a characterful, nasal tone; 0.8+ starts to whistle.",
  "sampler:sustain": "Level held while the key is down (1 = the sample as is). At 0 the sound ends after decay_ms (shortening one-shots).",
  "sampler:filter_env": "How far the cutoff opens along with the amp envelope (attack, decay); 1 is about +3 octaves. With a low cutoff and this raised, only the start is bright and the rest is muffled (pluck-like).",
  "sampler:filter_type": "Filter applied to the sample. off (default) bypasses it. lp12 / lp24 cut the highs for a muffled sound (24 is steeper), hp cuts the lows for a thin, light sound, bp keeps only the mids (telephone, radio), notch removes only the area around the cutoff.",
  "sampler:vel_cutoff": "How much softer notes lower the cutoff (at 1 the softest notes are 3 octaves darker). Hard playing is bright and soft playing round, like an acoustic instrument.",
  "sampler:key_track": "On (default): pitch (and length) follow the key played. Off: every key plays at the original pitch and length (drum one-shots, sound effects, vocal chops arranged purely rhythmically).",
  "sampler:root": "The sample's own pitch (MIDI note number, 60 = C4). This key plays the sample at its original speed; keys further away are pitch-shifted faster or slower. Match it to the sample's actual pitch.",
  "sampler:release_ms": "Fade time after the note ends. Short stops cleanly without a click; long lets the tails overlap.",
  "sampler:attack_ms": "Rise time. 2 ms (the default) keeps the sharp start of the sample as is. Tens of ms soften the hit; hundreds of ms make it swell in (string- or pad-like, a reverse-style swell).",
  "sampler:decay_ms": "Time to fall to the sustain level after the attack. No effect when sustain is 1. Shorten it and lower sustain to turn long samples into short, crisp notes.",
  "sampler:loop": "When on, loops between loop_start and loop_end while the key is held to sustain the sound (long pads and drones from short samples; fades out with the release when let go). Off (default) plays once to the end.",
  "sampler:loop_start": "Loop start position (as a fraction of the sample length). Placing it on a stable part around 0.2-0.5, past the attack, sustains naturally. At 0 the seam crossfade can't work (there's no material before the start).",
  "sampler:loop_end": "Loop end (fraction). The shorter the loop, the more mechanical the repetition (very short loops take on a buzzy pitch). Putting it before the sound has fully decayed keeps the level steady.",
  "sampler:loop_xfade_ms": "Time used to smooth the loop seam. At 0 the seam may click. For noise- or pad-like material, 100 ms or more makes the seam inaudible (keep it shorter for clearly pitched material).",
  "sampler:stereo": "Plays stereo samples in stereo (keeps the recording's width and placement). Off (default) sums to mono (easier to blend with other sounds, sits firmly in the center). No change for mono samples.",
  "sampler:slices": "Above 0, chops the sample at its onsets (attacks) into up to this many slices and maps them one per semitone upward from the root key (chopping drum loops or phrases to rearrange them). Each slice plays at its original pitch until the next onset. Keys outside the range are silent. Material with few onsets gives fewer slices.",
  "sampler:orig_bpm": "The original tempo of the sample (loop or phrase). Above 0, it is time-stretched without changing pitch to match the tempo at the start of the song (fitting drum loops to the song). 0 (default) = no stretching. Does not follow tempo changes partway through the song.",
  // pluck
  "pluck:decay": "How long the string rings. Short is muted and crisp; long sustains so arpeggio notes ring into each other.",
  "pluck:brightness": "String brightness (how long the highs last). Higher is a jangly steel-string sound; lower is a round, nylon-string tone.",
  "pluck:pick": "Pick hardness. Higher makes the attack hard and aggressive; lower is soft like fingerpicking.",
  // fm
  "fm:attack": "How fast the sound rises.",
  "fm:decay": "Time to fall to the sustain level. Longer for bells and electric pianos, shorter for mallets.",
  "fm:sustain": "Level while the key is held. At 0 it keeps decaying like a struck instrument.",
  "fm:release": "Tail after the key is released. Longer for bells.",
  "fm:ratio": "Modulator frequency as a multiple of the carrier. Integers (1, 2, 3) give instrument-like harmonics: 1 leans toward saw, 2 toward square. Non-integers (3.5, 1.41 etc.) give metallic, bell-like tones (bells, gongs).",
  "fm:index": "Amount of harmonics (brightness, hardness). 0 is a sine wave, 2-4 for electric piano and xylophone, 6+ for the sharpness of brass and bells. Gets deeper the harder you play.",
  "fm:index_decay": "Time for the modulation depth to settle. Short gives a hard sparkle only at the start that quickly rounds off (electric piano, mallets); long keeps it bright.",
  "fm:index_sustain": "Modulation depth that remains after it settles (as a fraction). At 0 the later part is nearly a sine (bell tails); at 1 the brightness doesn't change (organ, brass).",
  "fm:feedback": "Self-modulation of the modulator. Higher gives a gritty, saw-like tone (FM bass and leads).",
  // fm4
  "fm4:release": "Time to fade after the key is released (shared by all operators). Longer for bells and pads.",
  "fm4:feedback": "How much operator 4 modulates itself. Higher adds saw-like grit (brass, bass); near 1 it gets noisy.",
  "fm4:algorithm": "How the 4 operators are connected (→ = modulates, [ ] = heard as sound). 1 = 4→3→2→[1] (serial; brass, leads, gritty bass; the most complex harmonics), 2 = (4+3)→2→[1] (thick strings and brass), 3 = (3→2 + 4)→[1] (electric piano, clavinet), 4 = (4→3 + 2)→[1] (bass, woodwinds), 5 = 2→[1] and 4→[3] (DX electric piano and bells; default), 6 = 4→[1][2][3] (organ, brass section), 7 = 4→[3] and [1][2] (organ, marimba), 8 = [1][2][3][4] (sum of 4 sines; organ, flute).",
  "fm4:op1_ratio": "Frequency of operator 1 relative to the played note. It is a carrier (heard as sound) in every algorithm 1-8. For a modulator, integer ratios (1, 2, 3) give instrument-like harmonics, large integers (e.g. 14) a metallic attack (the electric piano 'tine'), and non-integers (1.41, 3.5) inharmonic, bell-like tones. Changing a carrier's ratio changes the pitch itself.",
  "fm4:op1_level": "Output of operator 1. For a carrier it is the volume; for a modulator it is the modulation depth (higher adds harmonics for a brighter, harder sound; near 1 it gets gritty and metallic). 0 = unused.",
  "fm4:op1_attack": "Rise of operator 1. For a carrier it is the volume rise; for a modulator the brightness grows gradually (0.05-0.2 for the brassy swell).",
  "fm4:op1_decay": "Time for operator 1 to fall to its sustain. A short decay on a modulator makes only the start bright, then quickly round (electric piano, bells, mallets).",
  "fm4:op1_sustain": "Level of operator 1 after its decay. A carrier at 0 dies away even while the key is held (piano, bells); near 1 it sustains (organ, brass, pads).",
  "fm4:op2_ratio": "Frequency of operator 2 relative to the played note. A carrier in algorithms 5-8; in 1-4 a modulator that drives operator 1. For a modulator, integer ratios (1, 2, 3) give instrument-like harmonics, large integers (e.g. 14) a metallic attack (the electric piano 'tine'), and non-integers (1.41, 3.5) inharmonic, bell-like tones. Changing a carrier's ratio changes the pitch itself.",
  "fm4:op2_level": "Output of operator 2. For a carrier it is the volume; for a modulator it is the modulation depth (higher adds harmonics for a brighter, harder sound; near 1 it gets gritty and metallic). 0 = unused.",
  "fm4:op2_attack": "Rise of operator 2. For a carrier it is the volume rise; for a modulator the brightness grows gradually (0.05-0.2 for the brassy swell).",
  "fm4:op2_decay": "Time for operator 2 to fall to its sustain. A short decay on a modulator makes only the start bright, then quickly round (electric piano, bells, mallets).",
  "fm4:op2_sustain": "Level of operator 2 after its decay. A carrier at 0 dies away even while the key is held (piano, bells); near 1 it sustains (organ, brass, pads).",
  "fm4:op3_ratio": "Frequency of operator 3 relative to the played note. A carrier in algorithms 5-8; a modulator in 1-4. For a modulator, integer ratios (1, 2, 3) give instrument-like harmonics, large integers (e.g. 14) a metallic attack (the electric piano 'tine'), and non-integers (1.41, 3.5) inharmonic, bell-like tones. Changing a carrier's ratio changes the pitch itself.",
  "fm4:op3_level": "Output of operator 3. For a carrier it is the volume; for a modulator it is the modulation depth (higher adds harmonics for a brighter, harder sound; near 1 it gets gritty and metallic). 0 = unused.",
  "fm4:op3_attack": "Rise of operator 3. For a carrier it is the volume rise; for a modulator the brightness grows gradually (0.05-0.2 for the brassy swell).",
  "fm4:op3_decay": "Time for operator 3 to fall to its sustain. A short decay on a modulator makes only the start bright, then quickly round (electric piano, bells, mallets).",
  "fm4:op3_sustain": "Level of operator 3 after its decay. A carrier at 0 dies away even while the key is held (piano, bells); near 1 it sustains (organ, brass, pads).",
  "fm4:op4_ratio": "Frequency of operator 4 relative to the played note. A carrier only in algorithm 8; otherwise a modulator (it can also modulate itself via feedback). For a modulator, integer ratios (1, 2, 3) give instrument-like harmonics, large integers (e.g. 14) a metallic attack (the electric piano 'tine'), and non-integers (1.41, 3.5) inharmonic, bell-like tones. Changing a carrier's ratio changes the pitch itself.",
  "fm4:op4_level": "Output of operator 4. For a carrier it is the volume; for a modulator it is the modulation depth (higher adds harmonics for a brighter, harder sound; near 1 it gets gritty and metallic). 0 = unused.",
  "fm4:op4_attack": "Rise of operator 4. For a carrier it is the volume rise; for a modulator the brightness grows gradually (0.05-0.2 for the brassy swell).",
  "fm4:op4_decay": "Time for operator 4 to fall to its sustain. A short decay on a modulator makes only the start bright, then quickly round (electric piano, bells, mallets).",
  "fm4:op4_sustain": "Level of operator 4 after its decay. A carrier at 0 dies away even while the key is held (piano, bells); near 1 it sustains (organ, brass, pads).",
  "fm4:vel_bright": "How much softer notes get shallower modulation (soft is round, hard is bright and hard, like an electric piano or piano). At 0 velocity only affects the volume.",
  // granular
  "granular:attack": "Rise time. 0.2-2 s for soft pads; short makes the grain cloud start abruptly.",
  "granular:sustain": "Level while the key is held. At 0 the sound ends after the decay (using the grain cloud as a short sound).",
  "granular:release": "Time to fade after the key is released. Long values leave the grain cloud as a lingering tail.",
  "granular:spread": "How far the grains scatter left and right. 0 = center (mono); higher spreads them across the whole stereo field. The volume stays the same when folded to mono.",
  "granular:root": "The key at which the source plays at its original pitch. Keys further away shift the grain pitch up or down (length and density don't change).",
  "granular:sample": "ID of the audio source the grains are cut from (sha256:...). Set by importing with import_sample using instrument: \"granular\" (you can also enter the ID of a source already in the project). Voices, instruments, ambiences, drum loops: anything works. Empty = silence.",
  "granular:position": "Where the grains are taken from (0 = start of the source, 1 = end). Put it on a vowel in a voice or a sustained part of an instrument to stretch that moment's tone forever (frozen time). Automating it morphs the timbre.",
  "granular:spray_ms": "Random forward/backward offset of each grain's position. 0 repeats the same spot mechanically (buzzy, robotic voice); tens of ms give a natural shimmer; hundreds of ms blend parts of the source into a cloud.",
  "granular:grain_ms": "Length of each grain. Short (5-30 ms) is grainy and crackly (the pitch gets vague too); 50-150 ms gives a smooth pad in which the source's tone is recognizable; long (200 ms+) lets fragments of the source be heard as they are.",
  "granular:density": "Grains per second. Few (up to about 10) are heard one by one as a scattered patter; once grain length x density exceeds 2, the grains overlap into a smooth sustained tone.",
  "granular:pitch_rand": "Random pitch offset per grain (± semitones). 0.1-0.3 adds chorus-like thickness, 1-2 a wavering, unstable sound, near 12 an unpitched cloud of sparkle.",
  "granular:window": "Volume envelope of each grain. hann = smooth hump (soft cloud; default), triangle = a bit more defined, trapezoid = short fades only at the edges (the grain content is heard as is), perc = sharp attack and decay (pattering, crackly, percussive grains).",
  "granular:scan": "How fast the read position advances while the key is held (1 = the source's original speed, 0.1 = stretched 10x, negative = backwards). 0 (default) freezes time. Wraps around to the other end at the ends of the source.",
  // additive
  "additive:attack": "Rise time. 0.3-2 s for pads.",
  "additive:sustain": "Level while the key is held. At 0 the sound ends after the decay (struck or plucked sounds).",
  "additive:release": "Time to fade after the key is released.",
  "additive:partials": "Number of sine waves summed. More reach higher harmonics for a brighter, more detailed sound but cost more CPU (64 is several times the subtractive synth). 48-64 for low or bright sounds; 16 is enough for high or round sounds.",
  "additive:tilt": "How much higher partials are attenuated per octave. -6 is a sawtooth spectrum (bright, strings), -12 is round (flute, soft pads), -18 or lower is close to a sine, 0 or above is harsh and glassy.",
  "additive:odd_even": "Balance of odd vs. even partials. -1 removes the evens (odd only = square wave, the hollow clarinet sound); +1 removes the odds (fundamental + evens = a bright, open octave stack, like an organ's 8'+4'). 0 = all.",
  "additive:formant_hz": "Position of a peak at a fixed frequency, independent of the note played (when formant_db is above 0). 300-800 Hz for 'o'/'a' vowels, 1500-2500 Hz for 'e'/'i', giving a vocal or wind-instrument character. Automate it to make it talk.",
  "additive:formant_db": "Height of the formant peak. 0 = none. 6-12 dB for an instrument-like color; 18 dB+ for strong, talking vowels.",
  "additive:formant_width": "Width of the peak in octaves. Narrow gives a sharp, nasal vowel; wide a gentle coloring.",
  "additive:damping": "How much faster higher partials die away. 0 = they don't (organ, pads), 0.3-0.6 for piano and electric piano, 1 for plucked strings and mallets (a bright start into a quickly rounded tail; partial k decays k/2 times as fast as partial 2).",
  "additive:inharmonic": "Progressively raises higher partials (like the stretch of piano strings). 0.2-0.4 for a piano-like tension; near 1 for bells and metal.",
  "additive:wobble": "Slow per-partial drift in pitch (±8 cents) and level (±20%). 0 is a clean, static electronic tone; 0.1-0.3 an alive analog feel or choir-like thickness; near 1 a heavily wavering, tape-like sound. The drift differs per note (and renders the same every time). New tracks start at 0.15.",
  // wavetable
  "wavetable:cutoff": "Lowpass filter. The tone mostly comes from the table and position, so normally leave it open and lower it only when you want a muffled sound.",
  "wavetable:resonance": "Emphasis around the cutoff.",
  "wavetable:attack": "How fast the sound rises. 0.3+ for soft pads.",
  "wavetable:decay": "Time to fall to the sustain level.",
  "wavetable:sustain": "Level while the key is held. 0 for plucks.",
  "wavetable:release": "Time to fade after the key is released. 1+ for pads.",
  "wavetable:filter_env": "How far the cutoff opens at the start of a note (1 is about +3 octaves). 0 = doesn't open (original behavior). filter_decay sets how long it takes to close again (at 0 it follows the amp ADSR).",
  "wavetable:unison": "Number of slightly detuned copies stacked on each note. 3-7 with detune for a thick, wide sound.",
  "wavetable:detune": "Spread of the unison voices (100 = one semitone). 15-30 is a good range.",
  "wavetable:position": "Which waveform in the table plays (0-1). Automating it morphs the timbre itself (wobble bass, evolving pads).",
  "wavetable:table": "The sequence of waveforms (scanned with position). analog = sine → triangle → saw → square; pulse = pulse width 50% → 5% (thin, nasal); vocal = vowels a → e → i → o → u (talking); sync = hard sync (glassy, metallic sweep; EDM leads and basses); organ = drawbars adding one harmonic at a time (round → glittering); fm = FM depth 0 → 8 (bell → murky growl); growl = growling vowels o → a → e (dubstep growls); fold = wavefolding (harsher the more it folds; neuro); harmonic = a band of bright harmonics moving from bottom to top; digital = saw quantized from 64 down to 2 steps (coarse digital). Tables made with make_wavetable (from harmonic blueprints, standard morphs or processing) are also set by their source ID. Tables made from audio with import_wavetable get a source ID (sha256:...) and let position move through how a single voice or instrument note changes over time (start = 0, end = 1).",
  "wavetable:pos_env": "How far position is offset at the start of a note, decaying back to position. Positive gives a bright, hard plucky attack; negative a sound that opens up later.",
  "wavetable:pos_decay": "Time for the pos_env offset to return. Short gives a snappy attack; long a slow change in timbre.",
  "wavetable:lfo_rate": "Speed of the periodic position modulation. Sync wobbles to the tempo (8th notes = BPM/30 Hz, e.g. 4.67 at 140 BPM).",
  "wavetable:lfo_depth": "Width of the position modulation. 0 = off. 0.3-0.6 for wobble bass and undulating pads.",
  "wavetable:warp": "Reshapes the waveform during playback (the table itself is unchanged; the amount is warp_amount). bend = pushes the peak forward (brighter, sharper), squeeze = narrows the first half (a nasal, PWM-like change), sync = reads the cycle several times (glassy sync), mirror = folds it symmetrically (hollow, fat), quantize = rounds values to steps (bit-reduced grit), fm = modulates with a sine at the same pitch (bell-like, metallic growl). Automating or modulating warp_amount makes it move.",
  "wavetable:warp_amount": "Amount of warp, 0-1. 0 = no warp. Moving it changes the timbre on an axis separate from the table position (adds a second motion to wobbles and growls).",
  // eq
  "eq:low_gain_db": "Low shelf (below low_freq). Raise it for a fuller, heavier sound; lower it for a cleaner, lighter one. To remove muddiness, lower this first.",
  "eq:low_freq": "Corner frequency of the low shelf.",
  "eq:mid_gain_db": "Peak/dip centered on mid_freq. Presence for vocals and leads is around 1-3 kHz; boxiness is usually cleared by cutting 300-500 Hz.",
  "eq:mid_freq": "Center frequency of the mid peak.",
  "eq:mid_q": "Width of the mid peak. Higher is narrower and more pinpoint.",
  "eq:high_gain_db": "High shelf (above high_freq). Raise it for brightness and air; lower it to tame harshness and sizzle.",
  "eq:high_freq": "Corner frequency of the high shelf.",
  "eq:hp_freq": "Cuts below this at 12 dB/oct (20 = off). Cutting unneeded lows (below 80-150 Hz) on tracks other than bass and kick cleans up the low end and reduces masking.",
  "eq:lp_freq": "Cuts above this at 12 dB/oct (20000 = off). Tames harsh highs and noise and pushes the sound back.",
  // compressor
  "compressor:release_ms": "Time for the compression to recover. Short causes pumping; long is smooth.",
  "compressor:attack_ms": "Time before compression kicks in. Short squashes the attack too for a rounder sound; long keeps the initial hit while compressing the body (drum punch).",
  "compressor:ratio": "Compression strength. 2-4 evens out levels naturally; 8+ gives a tightly squashed texture.",
  "compressor:threshold_db": "Levels above this start being compressed. The lower it is, the stronger the compression.",
  "compressor:knee_db": "Width over which compression eases in around the threshold. 0 is abrupt (hard knee); larger is more natural. 6-12 for vocals and buses, 0-3 for crushing drums.",
  "compressor:makeup_db": "Raises the level back up to make up for the compression.",
  "compressor:detector": "How the level is measured. peak reacts to instantaneous peaks and clamps them quickly (drums, peak control); rms reacts to the average level and is smoother (vocals, buses, evening out levels).",
  "compressor:sc_hpf_hz": "Cuts the lows only for level detection (20 = off). Keeps kick and bass lows from making the compressor pump. 80-150 for the full mix or buses.",
  "compressor:character": "Compressor character. clean is transparent compression with no coloration. vca recovers more slowly after long compression (auto-release) for a cohesive sound on buses and the full mix. fet grabs very fast and adds distortion the harder it works, an aggressive sound that pushes drums, vocals and bass forward. opto grabs a little slower, recovers the first half fast and the rest slowly: smooth, natural compression for vocals, bass and pads.",
  "compressor:lookahead_ms": "Delays the audio by this much so compression can start early (catches the initial peak even with a fast attack). 1-5 reliably controls peaks. The engine compensates for the delay (cannot be automated).",
  // reverb
  "reverb:damping": "High-frequency damping of the reverb. Higher gives a dark, soft reverb; lower a bright, sparkly one.",
  "reverb:character": "room is the natural sound of a room. plate is a dense, bright plate-style reverb, a classic for adding sheen to vocals and snares. hall is the long, wide sound of a large hall (1.6x longer at the same size; strings, pads, ballads). chamber is the dense, bright, shorter sound of a stone room (vocals, drums). shimmer is a hall whose tail rises an octave into sparkle (ambient, pads, guitar; amount set by shimmer).",
  "reverb:mix": "How much reverb is mixed in. 0.1-0.2 for a subtle space, 0.4+ for a dreamy one. Heavy reverb on drums or bass muddies the mix, so keep it modest there.",
  "reverb:size": "Size of the space (length of the reverb). Small is a room, large is a hall.",
  "reverb:predelay_ms": "Gap between the dry sound and the start of the reverb. 10-30 ms keeps vocals and instruments defined and in front of the reverb. Larger values suggest a bigger space.",
  "reverb:gate_ms": "Gated reverb: cuts the reverb this long after the incoming sound stops (0 = off). For an '80s snare use size 0.8+ with gate 150-300 for a big, short splash.",
  "reverb:shimmer": "With character set to shimmer, how much of the tail is pitched up an octave and fed back. More stacks the sparkle up toward the ceiling. 0.3-0.6 is easy to use.",
  "reverb:modulation": "Slightly modulates the inside of the reverb to soften the metallic ringing of long tails (specific notes hanging on), making them smoother. 0.2-0.5 makes long tails on pads, vocals and piano sound natural. Too much makes the pitch of the tail waver slightly (chorus-like).",
  "reverb:low_mult": "Reverb time multiplier below 250 Hz. Lower it to reduce low-end mud and tighten up (0.5-0.8 is standard in a mix, so the tail doesn't clash with bass and kick). Higher gives heavy, long cathedral lows.",
  "reverb:high_mult": "Reverb time multiplier above 4 kHz (works together with damping). Lower it so the highs die first, like a real room, for a calmer sound; raise it for a long, bright plate-like tail (lower it if sibilance stands out).",
  "reverb:early": "Amount of the first reflections off the walls (a few to tens of ms). More makes the room size and the distance to the source clearer (for a distant source, raise this and the mix). 0.3-0.6 places acoustic instruments and vocals in a room. Long in hall, short and weak in plate (a plate has no walls).",
  // distortion
  "distortion:tone": "Lowpass that smooths the fizz after the distortion. Lower for a fat, dark distortion; higher for a bright, crunchy one.",
  "distortion:mix": "Blend of the dry and distorted sound. 1.0 is fully distorted; 0.3-0.6 is parallel distortion that keeps the core of the dry sound.",
  "distortion:drive_db": "Depth of the distortion. 6-12 for warm saturation, 18-30 for rock distortion, 30+ for metal and extreme distortion. For guitar-like sounds, a square wave plus high drive is the go-to.",
  "distortion:level_db": "Output level. Distortion raises the loudness, so bring it back down here.",
  // amp
  "amp:gain_db": "Depth of distortion (preamp gain). Up to 10 is clean, 15-25 crunch, around 30 overdrive, 40+ metal-level high gain. More gain also lengthens the sustain.",
  "amp:tone": "Brightness after the distortion. Lower for fat and round; higher for an edgy, chunky bite.",
  "amp:level_db": "Output level. Raising the gain greatly increases the loudness, so bring it back down here.",
  "amp:presence": "High-end edge (3 kHz and up). Raise it to bring out the pick attack; too much becomes harsh.",
  "amp:cab": "Speaker cabinet coloration (shaped to 80 Hz-4.5 kHz). OFF is a full-range direct line; normally leave it ON.",
  // sidechain
  "sidechain:release_ms": "Time to come back up; this sets the 'swing' of the pumping. Tip: match it to the beat, around an 8th note (60000/BPM/2 ms); e.g. 200-230 ms at 128 BPM feels good.",
  "sidechain:attack_ms": "How fast it ducks to the bottom. Shorter lets the start of the kick punch through more clearly.",
  "sidechain:threshold_db": "Ducks when the source exceeds this. Lower is more sensitive.",
  "sidechain:source": "ID of the track used as the trigger signal (trk_xxxxxx). Usually the kick drum track. Does nothing while empty. Example: set_param path=fx/<fx_id>/source value=\"trk_drm001\"",
  "sidechain:duck_db": "How deep it ducks on each kick. 6-10 for a pleasant pump; 12+ for a deep, EDM-style dip.",
  // delay
  "delay:tone": "Brightness of the echoes (lowpass). Lower for analog/tape-style echoes that darken with each repeat; higher for a crisp digital delay.",
  "delay:feedback": "How many times the echo repeats. 0.2 gives 2-3 repeats, 0.5 goes on for a long time, 0.8+ barely stops.",
  "delay:mix": "How much echo is mixed in. 0.15-0.3 is subtle; around 0.5 is prominent.",
  "delay:duck_db": "How much the echoes are ducked while the dry sound is playing (ducking delay). Keeps the words of vocals and leads clear, with echoes heard only on held notes and between phrases. 3-6 is standard.",
  "delay:time_ms": "Interval between echoes. Usually match it to the tempo: quarter note = 60000/BPM ms, dotted 8th = 45000/BPM ms (500 / 375 at 120 BPM). 30-80 ms for doubling and slapback.",
  "delay:ping_pong": "Bounces the echoes alternately left and right for a wide spread.",
  "delay:sync": "Locks the echo interval to the song tempo (1/4 = quarter note, 1/8d = dotted 8th, 1/8t = 8th-note triplet). off uses time_ms. Follows tempo changes (the length is limited by the buffer, about 1.3 s at 48 kHz).",
  "delay:type": "digital is clean, crisp repeats. tape is a tape echo: a slight wobble from speed variation, and repeats round off and saturate without the lows building up (dub, rock, vocals). bbd is an analog BBD: warm repeats that get darker the longer the time (synths, guitar). multitap places read points at even divisions of the time by taps for rhythmic repeats (alternating left/right with ping_pong).",
  "delay:taps": "Number of multitap read points (2-4). 3 gives triplets, 4 gives 16ths (with the time set to a quarter note).",
  // chorus
  "chorus:mix": "How much of the modulated sound is mixed in. 0.5 gives the densest chorus.",
  "chorus:rate_hz": "Modulation speed. 0.3-1 for a slow, wide spread; 3+ wobbles like vibrato.",
  "chorus:depth_ms": "Modulation depth. 1-3 for natural thickness; 5+ makes the wobble clearly audible ('80s style).",
  "chorus:delay_ms": "Offset from the dry sound. Short (3-6) leans toward a metallic flanger; long (15-25) sounds like two players doubling.",
  // tape
  "tape:crackle": "Vinyl pops and crackles. 0.2-0.4 gives an old-record feel (a lo-fi hip hop staple); higher makes them more frequent and louder. Turn off wow and use only hiss and this for a vinyl sound.",
  "tape:tone": "High-frequency roll-off (lowpass). Lower for a more muffled, older recording; below 3000 sounds like radio or telephone.",
  "tape:wow": "Slow pitch drift from speed variation (about 0.5 Hz). 0.2-0.4 for a nostalgic wobble; 0.8+ for a woozy, stretched-cassette sound.",
  "tape:flutter": "Fast speed variation (about 6.5 Hz) that causes a fine tremble. Higher gives a worn, warbly texture.",
  "tape:saturation": "Tape saturation. Louder sounds are squashed round, warm and thick. Higher also lowers the peaks.",
  "tape:hiss": "Tape hiss. 0.1-0.3 adds air; higher increases the lo-fi feel.",
  "tape:bits": "Coarseness of the quantization. 16 = off, 8-12 for a gritty sampler sound, 4-6 for harsh destruction.",
  // multiband
  "multiband:release_ms": "How fast compression recovers (shared by all bands).",
  "multiband:attack_ms": "How fast compression kicks in (shared by all bands).",
  "multiband:low_gain_db": "Level of the low band after compression. Can also be used as a per-band EQ.",
  "multiband:low_freq": "Frequency that splits the low and mid bands. 120-250 to put only the kick and bass in the low band.",
  "multiband:mid_gain_db": "Level of the mid band after compression. Can also be used as a per-band EQ.",
  "multiband:high_gain_db": "Level of the high band after compression. Can also be used as a per-band EQ.",
  "multiband:high_freq": "Frequency that splits the mid and high bands. 3000-6000 to separate vocal harshness and cymbals into the high band.",
  "multiband:low_threshold_db": "The low band is compressed above this level.",
  "multiband:low_ratio": "Compression strength of the low band. 1 = no compression.",
  "multiband:mid_threshold_db": "The mid band is compressed above this level.",
  "multiband:mid_ratio": "Compression strength of the mid band. 1 = no compression.",
  "multiband:high_threshold_db": "The high band is compressed above this level.",
  "multiband:high_ratio": "Compression strength of the high band. 1 = no compression.",
  // transient
  "transient:attack_db": "Boosts or cuts the transient (the first instant of a hit). Higher sharpens the edges of drums and guitars; lower softens them and pushes them back.",
  "transient:sustain_db": "Boosts or cuts the tail. Lower tightens drum ring and room sound; higher makes it fatter and longer.",
  // limiter
  "limiter:release_ms": "How fast the level recovers. Short is louder but prone to distortion and pumping; long is natural.",
  "limiter:input_db": "How much the input is raised. More pushes against the ceiling for more loudness but squashes the dynamics. Streaming services normalize to -14 LUFS, so overdoing it gains nothing (check with analyze_audio's streaming).",
  "limiter:ceiling_db": "Output ceiling (true peak, including peaks between samples). -1 for streaming, -2 for very loud songs.",
  // width
  "width:width": "Stereo width. 0 = mono, 1 = unchanged, 2 = wide (left/right difference doubled). Too wide thins out in mono.",
  "width:mono_below_hz": "Collapses sound below this to the center (20 = off). 100-150 on the full mix or a synth bus anchors the bass and keeps it full in mono.",
  "width:decorrelate": "Widens even mono sources by creating left/right differences (adds a copy convolved with sparse noise to the side signal). It cancels out in mono, returning to the original. Weakened on transients so hits don't smear. For pads, choruses and stacked vocals.",
  // dynamic_eq
  "dynamic_eq:release_ms": "How fast it recovers.",
  "dynamic_eq:attack_ms": "How fast it starts cutting.",
  "dynamic_eq:ratio": "How strongly it cuts.",
  "dynamic_eq:threshold_db": "Cuts by however much the band's level exceeds this.",
  "dynamic_eq:source": "Empty = detects from its own sound (cuts only when that band is loud, taming sibilance or mud). Enter a track ID to cut itself only while that track is playing in this band (e.g. set the vocal track on the backing to clear 2-4 kHz). Example: set_param path=fx/<fx_id>/source value=\"trk_vox001\"",
  "dynamic_eq:freq": "Center of the band to control. Vocal sibilance 5000-8000, mud 200-400, carving space between vocals and backing 2000-4000.",
  "dynamic_eq:q": "Width of the band. Higher is narrower.",
  "dynamic_eq:range_db": "Upper limit on how much it cuts.",
  // convolution
  "convolution:mix": "Proportion of the reverb. 1 when inserted on a send bus.",
  "convolution:ir": "ID of the reverb (impulse response) audio source to convolve with (sha256:...). Set by importing a WAV recording of a room, hall, church, spring, plate etc. with import_ir. Empty = bypass.",
  "convolution:wet_db": "Level of the reverb. Levels are normalized across IRs.",
  "convolution:length": "Shortens the end of the IR to cut the reverb short (with a smooth fade-out). Changing it briefly interrupts the reverb.",
  // resonance
  "resonance:release_ms": "How fast it returns to normal after a resonance goes away.",
  "resonance:threshold_db": "How many dB above its surroundings a peak must stand out to count as a resonance. Smaller values act on finer detail.",
  "resonance:mix": "Proportion of the processed sound.",
  "resonance:width": "Width of the surrounding region (in octaves) a peak is compared against. Narrow catches only thin ringing; wide also cuts broader bumps.",
  "resonance:depth_db": "Upper limit on how much resonances are cut.",
  "resonance:low_hz": "Frequencies below this are left untouched.",
  "resonance:high_hz": "Frequencies above this are left untouched.",
  // virtual_bass
  "virtual_bass:freq": "Harmonics are generated from sound below this frequency.",
  "virtual_bass:amount": "Amount of harmonics added. Too much gets muddy.",
  "virtual_bass:remove_lows": "How much of the original lows to remove (the harmonics make up for it). Keeps lows the speakers can't reproduce from eating up headroom.",
  // clipper
  "clipper:mix": "Blend with the dry sound (parallel clipping).",
  "clipper:drive_db": "How much the level is raised before clipping. More flattens the peaks and pushes the sound forward (2-6 on drum buses and before the master, 12+ for bass distortion).",
  "clipper:ceiling_db": "Level at which it clips.",
  "clipper:mode": "soft squashes smoothly (tanh), hard cuts at the ceiling (hard and fast), fold folds back whatever exceeds it (more harmonics, metallic).",
  // bitcrush
  "bitcrush:bits": "Resolution of the sound. 8 sounds like a NES; 4 or below is heavily gritty.",
  "bitcrush:downsample": "Holds each value for this many samples. Higher makes the highs rougher, like a radio or game console.",
  // tremolo
  "tremolo:stereo": "0 = both sides together (tremolo); 1 = left and right in opposite directions (auto-pan).",
  "tremolo:rate_hz": "Modulation speed when sync is off.",
  "tremolo:depth": "Depth of the volume modulation. 1 goes all the way to silence.",
  "tremolo:shape": "Shape of the modulation. square chops like a stutter; saw_down gives chops with a strong start.",
  // phaser
  "phaser:feedback": "Higher gives a stronger, swooshy character.",
  "phaser:mix": "Blend with the dry sound (1 = half and half, the classic phase cancellation).",
  "phaser:rate_hz": "Sweep speed. 0.1-0.5 is slow and relaxed; 2+ makes the sweep obvious.",
  "phaser:depth": "Width of the sweep.",
  "phaser:stages": "Number of allpass stages. More gives more notches and a denser effect.",
  "phaser:center_hz": "Center of the swept range.",
  // flanger
  "flanger:feedback": "Higher sounds more metallic (negative gives a different character).",
  "flanger:rate_hz": "Speed of the jet-plane-like sweep.",
  "flanger:depth_ms": "How far the delay is swept.",
  "flanger:delay_ms": "Center delay. Shorter rings in a higher range.",
  // trance_gate
  "trance_gate:depth": "How much it lowers the level when closed. 1 = down to silence.",
  "trance_gate:pattern": "Which of the 16 sixteenth-note steps let the sound through. trance is the classic trance gate, offbeat lets only the offbeats through. 16th retriggers every 16th (smooth makes the steps audible).",
  "trance_gate:smooth_ms": "Open/close speed. Short is sharp; long is soft.",
  // auto_filter
  "auto_filter:cutoff": "Center frequency.",
  "auto_filter:resonance": "Emphasis around the cutoff. Higher makes it zap.",
  "auto_filter:rate_hz": "Speed when sync is off.",
  "auto_filter:mode": "lowpass cuts the highs for a darker sound, highpass cuts the lows for a lighter sound (a build-up staple), bandpass sounds like a wah.",
  "auto_filter:depth": "Range moved by the LFO (in octaves). At 0 it stops, so only cutoff automation moves it.",
  "auto_filter:shape": "Shape of the motion. saw_down gives wah-like chops that open at the start of each note and close.",
  "auto_filter:env_amount": "How much louder input opens the filter (envelope follower). For a funk auto-wah, use bandpass with 2-3.",
  // volume_shaper
  "volume_shaper:release": "Fraction of the period spent recovering.",
  "volume_shaper:sync": "Ducking period (1/4 = every quarter note = pumping in time with a four-on-the-floor kick).",
  "volume_shaper:depth_db": "How much it ducks at the start of each period. 6-12 for bass and pads; 18+ for obvious pumping.",
  "volume_shaper:curve": "pump ducks fast and recovers smoothly (like sidechain compression), linear recovers in a straight line, gate stays down until just before it recovers.",
  // eq8
  "eq8:output_db": "Level after the EQ. Bring big boosts back down so you can compare without being fooled by loudness differences.",
  "eq8:dyn_attack_ms": "How fast dynamic bands start moving.",
  "eq8:dyn_release_ms": "How fast dynamic bands return.",
  // saturation
  "saturation:tone": "Brightness tilt of the saturated sound (-1 dark to 1 bright, ±6 dB). Lower it if the harmonics get harsh.",
  "saturation:mix": "Blend with the dry sound (parallel saturation; 0.3-0.5 fattens while keeping the attack).",
  "saturation:drive_db": "How hard it is driven. Quiet sounds keep their level while louder sounds get squashed more. 6-12 for warmth and density, 18+ for clear distortion.",
  "saturation:type": "tape squashes smoothly and round and adds density (buses, master). tube adds even harmonics for a fat, warm sound (vocals, bass, electric piano). transistor is edgy and rough (drums, guitar). soft_clip sticks to a fixed level (loudness).",
  "saturation:output_db": "Level after the effect.",
  // deesser
  "deesser:threshold_db": "Starts reducing when the highs exceed this. Lower catches more 's' sounds.",
  "deesser:freq": "Highs above this are detected and reduced. Female vocals 6000-8000, male 4000-6000, harsh hats and cymbals 8000+.",
  "deesser:range_db": "Maximum reduction. 4-8 is natural; 12+ easily sounds lispy.",
  // gate
  "gate:release_ms": "Closing speed. Short cuts off tightly (the classic gate effect); long fades away naturally.",
  "gate:attack_ms": "Opening speed. Shorter emphasizes the attack (too short can click on low sounds).",
  "gate:threshold_db": "Opens for sounds louder than this. Set it above bleed, amp noise and reverb tails, and below the sound you want to keep.",
  "gate:source": "Empty = opens and closes on its own sound. Enter a track ID to open only while that track is playing (e.g. chopping bass or pads in time with the kick). Example: set_param path=fx/<fx_id>/source value=\"trk_drm001\"",
  "gate:range_db": "How much it lowers the level when closed. 80 = silence; 10-20 for a gentle gate (keeps some bleed, sounds natural).",
  "gate:hold_ms": "Time to wait after the level drops below the threshold before closing (so it doesn't chatter in the middle of a note).",
  "gate:hysteresis_db": "Sets the closing threshold this much below the opening threshold (prevents chattering at the boundary).",
  // pitch_shift
  "pitch_shift:mix": "Blend with the dry sound (1 = shifted sound only).",
  "pitch_shift:semitones": "How many semitones to shift (12 = up an octave, -12 = down). ±12 on vocals for a different-sounding voice or octave layering; 5 or 7 to layer fourths or fifths.",
  "pitch_shift:cents": "Fine pitch (100 per semitone). ±5-15 mixed in lightly with the dry sound gives a doubling-like thickness.",
  // harmonizer
  "harmonizer:spread": "With 2 voices, how far voice 1 is panned left and voice 2 right.",
  "harmonizer:mix": "Level of the added voices (0.5 is about as loud as the original).",
  "harmonizer:interval1": "How many semitones voice 1 is shifted from the original (3 = minor 3rd, 4 = major 3rd, 7 = 5th, 12 = octave, -12 = octave below). Not scale-aware: it always moves by the same interval.",
  "harmonizer:interval2": "Interval of voice 2 (when voices is 2).",
  "harmonizer:voices": "Number of voices to layer.",
  // pitch_correct
  "pitch_correct:key": "Key of the song (tonic).",
  "pitch_correct:scale": "The set of notes to snap to. chromatic snaps to any of the 12 notes (usable without knowing the key). major / minor etc. avoid snapping to out-of-key notes when matched to the song's key.",
  "pitch_correct:speed_ms": "How fast it snaps. 0-5 for the robotic hard-tune effect, 20-50 for natural correction, 100+ for gentle nudging (vibrato remains).",
};

/** eq8 の 1 バンドぶんのつまみ(名前の後半・表示名の後半・説明)。b1_〜b8_ の 8 本に同じものを入れる */
const EQ8_BAND: [string, string, string][] = [
  ["on", "on", "Enables this band. When off, the band is bypassed."],
  ["type", "type", "bell raises or lowers the area around the frequency (width set by Q). low_shelf / high_shelf raise or lower everything below / above it (weight, brightness). low_cut / high_cut remove everything below / above it (12 dB/oct; the _24 versions are a steeper 24 dB/oct). notch carves a deep cut at a single point (removing hum or ringing)."],
  ["freq", "freq", "Frequency to act on. Bass weight 60-120, mud 200-500, honk 800-1500, presence and harshness 2k-5k, air 10k and up. Cuts have no effect at 20 or below / 20000 or above."],
  ["gain_db", "gain", "Boost/cut amount for bell and shelves. Cutting tends to sound more natural than boosting (±3-6 is a good guide)."],
  ["q", "Q", "How narrow it is. For bell, 0.5-1 is broad and musical; 4+ is narrow and surgical (removing ringing). For shelves and cuts 0.707 is neutral; raising it adds a bump at the corner."],
  ["threshold_db", "threshold", "Dynamic mode (when range is not 0): the gain moves by however much this band's level exceeds this."],
  ["range_db", "range", "Maximum dynamic movement (0 = an ordinary static EQ). Negative cuts only when the band is loud (taming harshness, mud or boominess only while it occurs); positive boosts only when it is loud. Moves by 2/3 of the excess (3:1). Bell and shelves only."],
  ["stereo", "channel", "stereo processes both channels, mid only the center (vocals, kick, bass), side only the stereo width. A low_cut on the side tightens the lows; boosting the highs on the side brightens the width."],
];
for (let b = 1; b <= 8; b++) {
  for (const [n, label, desc] of EQ8_BAND) {
    LABEL_EN[`eq8:b${b}_${n}`] = `Band ${b} ${label}`;
    DESC_EN[`eq8:b${b}_${n}`] = desc;
  }
}

/** 名前を読みやすく: filter_env → Filter env、gain_db → Gain (dB) */
function humanize(name: string): string {
  const unit = name.endsWith("_db") ? " (dB)" : name.endsWith("_ms") ? " (ms)" : name.endsWith("_hz") ? " (Hz)" : "";
  const base = name.replace(/_(db|ms|hz)$/, "").replace(/_/g, " ");
  return base.charAt(0).toUpperCase() + base.slice(1) + unit;
}

/** つまみの表示名(日本語のときは `ja` のまま) */
export function paramLabel(kind: string | null | undefined, name: string, ja: string): string {
  if (!isEn()) return ja;
  return (kind && LABEL_EN[`${kind}:${name}`]) || LABEL_EN[name] || humanize(name);
}

/** つまみの説明(日本語のときは `ja` のまま。英語の対訳が無ければ空) */
export function paramDesc(kind: string | null | undefined, name: string, ja: string): string {
  if (!isEn()) return ja;
  return (kind && DESC_EN[`${kind}:${name}`]) || DESC_EN[name] || "";
}

/** 単位の表示(定義の単位はほとんど英語の記号。日本語の「半音」だけ英語では st) */
export function unitText(unit: string | null | undefined): string {
  if (!unit) return "";
  return isEn() && unit === "半音" ? "st" : unit;
}
