import { isEn } from "./i18n.svelte";

// AI(MCP)のツール名の日本語表示(英語は LABELS_EN)。ヘッダーの作業中表示とチャットの ⚙ 表示で共通。
// 以前は 36 個のうち 7〜9 個にしか訳が無く(今は 41 個)、2 か所に別々に書かれていた。

interface ToolLabel {
  /** チャットの ⚙ 表示(名詞) */
  short: string;
  /** ヘッダーの作業中表示(「AI が…」に続く) */
  doing: string;
}

const LABELS: Record<string, ToolLabel> = {
  // 基本
  get_project: { short: "プロジェクトを確認", doing: "プロジェクトを読んでいます" },
  apply_commands: { short: "編集を適用", doing: "編集しています" },
  undo: { short: "取り消し", doing: "取り消しています" },
  redo: { short: "やり直し", doing: "やり直しています" },
  checkpoint: { short: "チェックポイント作成", doing: "チェックポイントを作成しています" },
  revert_to: { short: "チェックポイントへ巻き戻し", doing: "巻き戻しています" },
  revert: { short: "編集を取り消し", doing: "編集を取り消しています" },
  get_history: { short: "履歴を確認", doing: "履歴を確認しています" },
  list_params: { short: "パラメータを確認", doing: "パラメータを確認しています" },
  get_changes: { short: "変更を確認", doing: "変更を確認しています" },
  get_guide: { short: "定石を確認", doing: "定石を読んでいます" },
  // 構成
  duplicate_clips: { short: "クリップを複製", doing: "クリップを複製しています" },
  insert_bars: { short: "小節を挿入", doing: "小節を挿入しています" },
  change_meter: { short: "拍子を変える", doing: "小節の拍子を変えています" },
  delete_bars: { short: "小節を削除", doing: "小節を削除しています" },
  bounce_track: { short: "トラックを音声にする", doing: "トラックを音声に描き出しています" },
  resample_to_sampler: { short: "サンプラーへリサンプリング", doing: "トラックを描き出してサンプラーの音源にしています" },
  export_audio: { short: "書き出し", doing: "WAV に書き出しています" },
  export_midi: { short: "MIDI に書き出し", doing: "MIDI ファイルに書き出しています" },
  import_midi: { short: "MIDI の読み込み", doing: "MIDI ファイルを読み込んでいます" },
  import_musicxml: { short: "MusicXML の読み込み", doing: "MusicXML を読み込んでいます" },
  // 分析
  analyze_audio: { short: "音を聴いて確認", doing: "音を聴いています" },
  check_distortion: { short: "歪み・潰れを確認", doing: "歪みと潰れを測っています" },
  analyze_harmony: { short: "キーとコードを確認", doing: "キーとコードを調べています" },
  analyze_rhythm: { short: "リズムを確認", doing: "リズムを調べています" },
  analyze_beats: { short: "テンポを測定", doing: "テンポを測っています" },
  analyze_reference: { short: "参考曲の構成を解析", doing: "参考曲の構成を読んでいます" },
  analyze_sound: { short: "音色を確認", doing: "音色を調べています" },
  compare_sounds: { short: "音を比較", doing: "音を比べています" },
  compare_mix: { short: "編集の前後を聴き比べ", doing: "編集の前後を聴き比べています" },
  master_mix: { short: "マスタリング", doing: "マスタリングしています" },
  import_ir: { short: "響き(IR)を読み込む", doing: "響きを読み込んでいます" },
  refine_by_words: { short: "言葉で音を追い込む", doing: "言葉に合わせて音を追い込んでいます" },
  match_sound: { short: "音色を似せる", doing: "音色を似せています" },
  // ノート
  transpose_notes: { short: "移調", doing: "移調しています" },
  shift_notes: { short: "ノートを移動", doing: "ノートを動かしています" },
  swing_notes: { short: "スウィング", doing: "ハネを付けています" },
  apply_groove: { short: "グルーブ", doing: "ノリを付けています" },
  add_ghost_notes: { short: "ゴーストノート", doing: "ゴーストノートを足しています" },
  transform_notes: { short: "旋律の変形", doing: "旋律を展開しています" },
  shape_automation: { short: "動きを付ける", doing: "オートメーションを書いています" },
  write_wobble: { short: "ワブルを書く", doing: "ワブルの速さのリズムを書いています" },
  critique_arrangement: { short: "編曲の点検", doing: "編曲を点検しています" },
  critique_mix: { short: "音とミックスの点検", doing: "音とミックスを点検しています" },
  apply_recipe: { short: "定番の手順", doing: "定番の手順を組んでいます" },
  set_character: { short: "音のつまみ", doing: "音のつまみを動かしています" },
  design_sound: { short: "言葉から音色", doing: "言葉から音色を作っています" },
  mutate_sound: { short: "音色の変種", doing: "音色の変種を作っています" },
  set_song_plan: { short: "曲の計画書", doing: "曲の計画を立てています" },
  get_design: { short: "設計を確認", doing: "曲の設計(計画と実際)を読んでいます" },
  propose_design: { short: "案を出す", doing: "案を出しています" },
  ask_user: { short: "質問", doing: "質問を用意しています" },
  write_chords: { short: "コードの伴奏", doing: "コード進行から伴奏を書いています" },
  write_arpeggio: { short: "アルペジオ", doing: "アルペジオを書いています" },
  write_bassline: { short: "ベースライン", doing: "ベースラインを書いています" },
  write_drums: { short: "ドラムの型", doing: "ドラムを置いています" },
  write_transition: { short: "区間のつなぎ", doing: "区間のつなぎを置いています" },
  suggest_progression: { short: "進行の候補", doing: "コード進行の候補を探しています" },
  critique_melody: { short: "旋律の点検", doing: "旋律を点検しています" },
  analyze_melody: { short: "旋律の構造", doing: "旋律の構造を読んでいます" },
  plan_melody: { short: "旋律の計画", doing: "旋律の計画を立てています" },
  realize_melody: { short: "計画から旋律", doing: "計画から旋律を作っています" },
  revise_melody: { short: "旋律の改稿", doing: "旋律を直しています" },
  save_plan: { short: "計画を保存", doing: "旋律の計画を保存しています" },
  edit_plan: { short: "計画を直す", doing: "旋律の計画を直しています" },
  delete_plan: { short: "計画を消す", doing: "旋律の計画を消しています" },
  get_plan: { short: "計画を読む", doing: "旋律の計画を読んでいます" },
  plan_log: { short: "計画の経緯", doing: "計画の経緯を読んでいます" },
  undo_plan: { short: "計画を戻す", doing: "計画の変更を戻しています" },
  develop_motif: { short: "動機の展開", doing: "動機から旋律を展開しています" },
  write_melody: { short: "旋律を作る", doing: "旋律の案を作って選んでいます" },
  write_polyrhythm: { short: "ポリリズム", doing: "ポリリズムを置いています" },
  write_polymeter: { short: "ポリメーター", doing: "ポリメーターを置いています" },
  set_meter_feel: { short: "拍の揺れ", doing: "長い拍と短い拍の比を変えています" },
  pitch_gesture: { short: "音程の表情", doing: "しゃくり・フォールなどを付けています" },
  set_vibrato: { short: "ビブラート", doing: "ビブラートを付けています" },
  add_ornament: { short: "装飾音", doing: "装飾音を付けています" },
  melody_lead: { short: "旋律のリード", doing: "旋律を少し先に鳴らしています" },
  note_dynamics: { short: "音の中の強弱", doing: "音の中の強弱・明るさを付けています" },
  strum_chord: { short: "ストローク", doing: "和音をストロークにしています" },
  drum_rudiment: { short: "ルーディメント", doing: "フラム・ロールなどを付けています" },
  articulate_notes: { short: "音の切り方", doing: "音の切り方をそろえています" },
  tremolo: { short: "トレモロ", doing: "トレモロにしています" },
  glissando: { short: "グリッサンド", doing: "グリッサンドを付けています" },
  shape_phrase: { short: "句の呼吸", doing: "句にテンポの揺れを付けています" },
  metric_modulation: { short: "テンポの読み替え", doing: "音価を読み替えてテンポを変えています" },
  hemiola: { short: "ヘミオラ", doing: "3 拍子を 2 拍ずつに聞かせています" },
  write_tihai: { short: "ティハイ", doing: "3 回繰り返して着地する句を置いています" },
  export_musicxml: { short: "譜面の書き出し", doing: "MusicXML に書き出しています" },
  modulate: { short: "変調(LFO)", doing: "つまみを LFO で揺らしています" },
  set_layer: { short: "音源の重ね", doing: "音源を重ねています" },
  set_macro: { short: "マクロ", doing: "マクロを設定しています" },
  sustain_pedal: { short: "ペダル", doing: "サステインペダルを焼き込んでいます" },
  set_note_condition: { short: "条件付きの発音", doing: "ループの回ごとの鳴り方を決めています" },
  quantize_notes: { short: "クオンタイズ", doing: "タイミングを揃えています" },
  scale_velocity: { short: "強さを調整", doing: "音の強さを調整しています" },
  // 音色
  list_presets: { short: "音色のプリセット一覧", doing: "音色のプリセットを探しています" },
  save_preset: { short: "音色のプリセットを保存", doing: "音色のプリセットを保存しています" },
  load_preset: { short: "音色のプリセットを適用", doing: "音色のプリセットを読み込んでいます" },
  delete_preset: { short: "音色のプリセットを削除", doing: "音色のプリセットを削除しています" },
  list_effect_presets: { short: "エフェクトのプリセット一覧", doing: "エフェクトのプリセットを探しています" },
  save_effect_preset: { short: "エフェクトのプリセットを保存", doing: "エフェクトのプリセットを保存しています" },
  load_effect_preset: { short: "エフェクトのプリセットを追加", doing: "エフェクトのプリセットを足しています" },
  delete_effect_preset: { short: "エフェクトのプリセットを削除", doing: "エフェクトのプリセットを削除しています" },
  find_similar_presets: { short: "似たプリセットを探す", doing: "似たプリセットを探しています" },
  list_soundfonts: { short: "SoundFont 一覧", doing: "SoundFont を確認しています" },
  set_soundfont_instrument: { short: "SoundFont の楽器を設定", doing: "楽器を設定しています" },
  // CLAP
  list_plugins: { short: "プラグイン一覧", doing: "プラグインを確認しています" },
  list_plugin_presets: { short: "プラグインのプリセット一覧", doing: "プラグインのプリセットを探しています" },
  load_plugin_preset: { short: "プラグインのプリセットを適用", doing: "プラグインのプリセットを読み込んでいます" },
  refine_plugin_params: { short: "プラグインのつまみを調整", doing: "プラグインのつまみを詰めています" },
  // 素材
  import_sample: { short: "サンプルを取り込み", doing: "サンプルを取り込んでいます" },
  import_wavetable: { short: "ウェーブテーブルを作る", doing: "音声からウェーブテーブルを作っています" },
  review_edits: { short: "直した所を確かめる", doing: "直した所の周りを確かめています" },
  make_wavetable: { short: "ウェーブテーブルを作り込む", doing: "ウェーブテーブルを作っています" },
  describe_wavetable: { short: "ウェーブテーブルを確かめる", doing: "ウェーブテーブルの中身を調べています" },
  wavetable_library: { short: "ウェーブテーブルの棚", doing: "ウェーブテーブルの棚を使っています" },
  import_audio_clip: { short: "音声を配置", doing: "音声を取り込んでいます" },
  transcribe_audio: { short: "譜起こし", doing: "譜起こししています" },
  separate_audio: { short: "パート分離", doing: "パートに分けています" },
  // GPT(Codex)の組み込みの動作
  command_execution: { short: "コマンドを実行", doing: "コマンドを実行しています" },
  web_search: { short: "Web を検索", doing: "Web を検索しています" },
};

/** 英語の表示(short はチャットの行、doing は「AI is …」に続く現在分詞の句) */
const LABELS_EN: Record<string, ToolLabel> = {
  // 基本
  get_project: { short: "Read the project", doing: "reading the project" },
  apply_commands: { short: "Apply edits", doing: "editing" },
  undo: { short: "Undo", doing: "undoing" },
  redo: { short: "Redo", doing: "redoing" },
  checkpoint: { short: "Create checkpoint", doing: "creating a checkpoint" },
  revert_to: { short: "Revert to checkpoint", doing: "reverting" },
  revert: { short: "Revert edits", doing: "reverting edits" },
  get_history: { short: "Check history", doing: "checking the history" },
  list_params: { short: "Check parameters", doing: "checking parameters" },
  get_changes: { short: "Check changes", doing: "checking changes" },
  get_guide: { short: "Read the guide", doing: "reading the guide" },
  // 構成
  duplicate_clips: { short: "Duplicate clips", doing: "duplicating clips" },
  insert_bars: { short: "Insert bars", doing: "inserting bars" },
  change_meter: { short: "Change meter", doing: "changing the time signature" },
  delete_bars: { short: "Delete bars", doing: "deleting bars" },
  bounce_track: { short: "Bounce track", doing: "bouncing a track to audio" },
  resample_to_sampler: { short: "Resample to sampler", doing: "resampling a track into the sampler" },
  export_audio: { short: "Export", doing: "exporting to WAV" },
  export_midi: { short: "Export MIDI", doing: "exporting a MIDI file" },
  import_midi: { short: "Import MIDI", doing: "importing a MIDI file" },
  import_musicxml: { short: "Import MusicXML", doing: "importing MusicXML" },
  // 分析
  analyze_audio: { short: "Listen and check", doing: "listening" },
  check_distortion: { short: "Check distortion", doing: "measuring distortion and squashing" },
  analyze_harmony: { short: "Check key and chords", doing: "analyzing key and chords" },
  analyze_rhythm: { short: "Check rhythm", doing: "analyzing the rhythm" },
  analyze_beats: { short: "Detect tempo", doing: "detecting the tempo" },
  analyze_reference: { short: "Analyze reference structure", doing: "analyzing the reference's structure" },
  analyze_sound: { short: "Check timbre", doing: "analyzing the timbre" },
  compare_sounds: { short: "Compare sounds", doing: "comparing sounds" },
  compare_mix: { short: "Compare before/after", doing: "comparing before and after" },
  master_mix: { short: "Mastering", doing: "mastering" },
  import_ir: { short: "Load IR", doing: "loading an impulse response" },
  refine_by_words: { short: "Refine sound by words", doing: "refining the sound to match the words" },
  match_sound: { short: "Match timbre", doing: "matching the timbre" },
  // ノート
  transpose_notes: { short: "Transpose", doing: "transposing" },
  shift_notes: { short: "Move notes", doing: "moving notes" },
  swing_notes: { short: "Swing", doing: "adding swing" },
  apply_groove: { short: "Groove", doing: "applying groove" },
  add_ghost_notes: { short: "Ghost notes", doing: "adding ghost notes" },
  transform_notes: { short: "Transform melody", doing: "transforming the melody" },
  shape_automation: { short: "Add movement", doing: "writing automation" },
  write_wobble: { short: "Write wobble", doing: "writing a wobble rhythm" },
  critique_arrangement: { short: "Review arrangement", doing: "reviewing the arrangement" },
  critique_mix: { short: "Review sound and mix", doing: "reviewing the sound and mix" },
  apply_recipe: { short: "Standard recipe", doing: "building a standard recipe" },
  set_character: { short: "Sound macros", doing: "adjusting the sound" },
  design_sound: { short: "Sound from words", doing: "designing a sound from words" },
  mutate_sound: { short: "Sound variations", doing: "making sound variations" },
  set_song_plan: { short: "Song plan", doing: "planning the song" },
  get_design: { short: "Check design", doing: "reading the song design (plan and actual)" },
  propose_design: { short: "Propose options", doing: "proposing options" },
  ask_user: { short: "Question", doing: "preparing a question" },
  write_chords: { short: "Chord accompaniment", doing: "writing an accompaniment from chords" },
  write_arpeggio: { short: "Arpeggio", doing: "writing an arpeggio" },
  write_bassline: { short: "Bassline", doing: "writing a bassline" },
  write_drums: { short: "Drum pattern", doing: "laying down drums" },
  write_transition: { short: "Transition", doing: "adding a transition" },
  suggest_progression: { short: "Progression ideas", doing: "looking for chord progressions" },
  critique_melody: { short: "Review melody", doing: "reviewing the melody" },
  analyze_melody: { short: "Melody structure", doing: "analyzing the melody's structure" },
  plan_melody: { short: "Melody plan", doing: "planning the melody" },
  realize_melody: { short: "Melody from plan", doing: "writing a melody from the plan" },
  revise_melody: { short: "Revise melody", doing: "revising the melody" },
  save_plan: { short: "Save plan", doing: "saving the melody plan" },
  edit_plan: { short: "Edit plan", doing: "editing the melody plan" },
  delete_plan: { short: "Delete plan", doing: "deleting the melody plan" },
  get_plan: { short: "Read plan", doing: "reading the melody plan" },
  plan_log: { short: "Plan history", doing: "reading the plan's history" },
  undo_plan: { short: "Undo plan change", doing: "undoing a plan change" },
  develop_motif: { short: "Develop motif", doing: "developing a melody from a motif" },
  write_melody: { short: "Write melody", doing: "writing and choosing melody ideas" },
  write_polyrhythm: { short: "Polyrhythm", doing: "adding a polyrhythm" },
  write_polymeter: { short: "Polymeter", doing: "adding a polymeter" },
  set_meter_feel: { short: "Beat feel", doing: "changing the long/short beat ratio" },
  pitch_gesture: { short: "Pitch gestures", doing: "adding scoops and falls" },
  set_vibrato: { short: "Vibrato", doing: "adding vibrato" },
  add_ornament: { short: "Ornaments", doing: "adding ornaments" },
  melody_lead: { short: "Melody lead", doing: "pushing the melody slightly ahead" },
  note_dynamics: { short: "In-note dynamics", doing: "shaping dynamics and brightness within notes" },
  strum_chord: { short: "Strum", doing: "strumming chords" },
  drum_rudiment: { short: "Rudiments", doing: "adding flams and rolls" },
  articulate_notes: { short: "Articulation", doing: "setting articulation" },
  tremolo: { short: "Tremolo", doing: "adding tremolo" },
  glissando: { short: "Glissando", doing: "adding a glissando" },
  shape_phrase: { short: "Phrase breathing", doing: "adding tempo rubato to phrases" },
  metric_modulation: { short: "Metric modulation", doing: "changing the tempo by metric modulation" },
  hemiola: { short: "Hemiola", doing: "phrasing triple meter in twos" },
  write_tihai: { short: "Tihai", doing: "adding a thrice-repeated cadence" },
  export_musicxml: { short: "Export score", doing: "exporting MusicXML" },
  modulate: { short: "Modulation (LFO)", doing: "modulating a parameter with an LFO" },
  set_layer: { short: "Layer instruments", doing: "layering instruments" },
  set_macro: { short: "Macro", doing: "setting up macros" },
  sustain_pedal: { short: "Pedal", doing: "baking in the sustain pedal" },
  set_note_condition: { short: "Conditional notes", doing: "setting per-loop note conditions" },
  quantize_notes: { short: "Quantize", doing: "quantizing timing" },
  scale_velocity: { short: "Adjust velocity", doing: "adjusting velocity" },
  // 音色
  list_presets: { short: "List sound presets", doing: "browsing sound presets" },
  save_preset: { short: "Save sound preset", doing: "saving a sound preset" },
  load_preset: { short: "Apply sound preset", doing: "loading a sound preset" },
  delete_preset: { short: "Delete sound preset", doing: "deleting a sound preset" },
  list_effect_presets: { short: "List effect presets", doing: "browsing effect presets" },
  save_effect_preset: { short: "Save effect preset", doing: "saving an effect preset" },
  load_effect_preset: { short: "Add effect preset", doing: "adding an effect preset" },
  delete_effect_preset: { short: "Delete effect preset", doing: "deleting an effect preset" },
  find_similar_presets: { short: "Find similar presets", doing: "finding similar presets" },
  list_soundfonts: { short: "List SoundFonts", doing: "checking SoundFonts" },
  set_soundfont_instrument: { short: "Set SoundFont instrument", doing: "setting the instrument" },
  // CLAP
  list_plugins: { short: "List plugins", doing: "checking plugins" },
  list_plugin_presets: { short: "List plugin presets", doing: "browsing plugin presets" },
  load_plugin_preset: { short: "Apply plugin preset", doing: "loading a plugin preset" },
  refine_plugin_params: { short: "Tweak plugin params", doing: "fine-tuning plugin parameters" },
  // 素材
  import_sample: { short: "Import sample", doing: "importing a sample" },
  import_wavetable: { short: "Make wavetable", doing: "making a wavetable from audio" },
  review_edits: { short: "Check edited parts", doing: "checking around the edited parts" },
  make_wavetable: { short: "Build wavetable", doing: "building a wavetable" },
  describe_wavetable: { short: "Inspect wavetable", doing: "inspecting a wavetable" },
  wavetable_library: { short: "Wavetable library", doing: "using the wavetable library" },
  import_audio_clip: { short: "Place audio", doing: "importing audio" },
  transcribe_audio: { short: "Transcribe", doing: "transcribing" },
  separate_audio: { short: "Separate stems", doing: "separating into stems" },
  // GPT(Codex)の組み込みの動作
  command_execution: { short: "Run command", doing: "running a command" },
  web_search: { short: "Search the web", doing: "searching the web" },
};

/** `mcp__glaux__` などの接頭辞を外したツール名 */
function bare(name: string): string {
  return name.replace(/^mcp__[^_]+__/, "");
}

/** チャットの ⚙ 表示用(訳が無ければツール名のまま) */
export function toolShort(name: string): string {
  const n = bare(name);
  return (isEn() ? LABELS_EN : LABELS)[n]?.short ?? n;
}

/** ヘッダーの作業中表示用(訳が無ければ「<ツール名> を実行しています」/ "running <ツール名>") */
export function toolDoing(name: string): string {
  const n = bare(name);
  if (isEn()) return LABELS_EN[n]?.doing ?? `running ${n}`;
  return LABELS[n]?.doing ?? `${n} を実行しています`;
}
